[nitpick]
minimum_version = "0.22.0"

[nitpick.styles]
include = [ "file-structure.toml", "flake8.toml", "isort.toml", "darglint.toml", "mypy.toml", "poetry.toml", "styleguide.toml",]

["setup.cfg".flake8]
docstring-style = "numpy"
format = "wemake"
ignore = "D100,D104,D401,W504,RST303,RST304,DAR103,DAR203"
max-complexity = 6
max-line-length = 80
show-source = true
strictness = "long"

["setup.cfg".isort]
include_trailing_comma = true
line_length = 80
multi_line_output = 3
use_parentheses = true

["setup.cfg".mypy]
allow_redefinition = false
check_untyped_defs = true
ignore_errors = false
ignore_missing_imports = true
implicit_reexport = false
local_partial_types = true
no_implicit_optional = true
strict_equality = true
strict_optional = true
warn_no_return = true
warn_redundant_casts = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true

[nitpick.files.absent]
".flake8" = "Move values to setup.cfg, section [flake8]"
".isort.cfg" = "Move values to setup.cfg, section [isort]"
".pyup.yml" = "Configure your CI with safety instead: https://github.com/pyupio/safety#using-safety-with-a-ci-service"
".travis.yml" = "Travis is shutting down, please switch to some other CI service"
Pipfile = "Use pyproject.toml instead"
"Pipfile.lock" = "Use pyproject.toml instead"
"mypy.ini" = "Move values to setup.cfg, section [mypy]"
"requirements.txt" = "Install poetry, run 'poetry init' to create pyproject.toml, and move dependencies to it"

[nitpick.files.present]
".editorconfig" = "A project should have an editor configuration"
".gitignore" = "A project should have `.gitignore` file"
"CHANGELOG.md" = "A project should have `CHANGELOG.md`"
"README.md" = "A project should have `README.md`"
"pyproject.toml" = "Install poetry and run 'poetry init' to create it"

[nitpick.files."setup.cfg"]
comma_separated_values = [ "flake8.ignore",]
